name: Feature Request
description: Suggest a new feature or enhancement for Shape
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please note that Shape is intentionally scoped to large, standardized, open data formats only.

        **Before submitting:** Please check our [Format Addition Policy](https://github.com/shapestone/shape/blob/main/CONTRIBUTING.md#format-addition-policy) if you're requesting a new format.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New format support
        - Performance improvement
        - API enhancement
        - Tooling/CLI improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when I try to parse X format because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like Shape to support...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I tried using... but it didn't work because...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and why this feature would be valuable
      placeholder: This would help me/my team...
    validations:
      required: true

  - type: textarea
    id: format-justification
    attributes:
      label: Format Justification (if requesting new format)
      description: |
        If you're requesting a new format, please justify why it meets our criteria:
        - Widely adopted (used across multiple industries)
        - Open standard (published specification or RFC)
        - Language agnostic (not specific to a single language/framework)
        - Stable (mature format with established usage)
        - General purpose (suitable for broad use cases)
      placeholder: |
        - Standard: [Link to RFC/specification]
        - Adoption: Used by [examples of widely-used projects]
        - Use cases: [general purpose applications]

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: |
        Example code:
        ```go
        // How I'd like to use this feature
        ```
